sudo: required
services:
  - docker

before_install:
  - docker build -t martinschinabeck/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true martinschinabeck/react-test npm test

after_success:
  - docker build -t martinschinabeck/multi-client ./client
  - docker build -t martinschinabeck/multi-nginx ./nginx
  - docker build -t martinschinabeck/multi-server ./server
  - docker build -t martinschinabeck/multi-worker ./worker

  # log in to Docker CLI  
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  
  # push images to docker hub
  - docker push martinschinabeck/multi-client
  - docker push martinschinabeck/multi-nginx
  - docker push martinschinabeck/multi-server
  - docker push martinschinabeck/multi-worker

  

